//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CardName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.CardName", typeof(CardName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players amount should be from 4 to 7. Actual value is {0}.
        /// </summary>
        public static string AmountPlayersExceptionMessageFormat {
            get {
                return ResourceManager.GetString("AmountPlayersExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bang.
        /// </summary>
        public static string Bang {
            get {
                return ResourceManager.GetString("Bang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrel.
        /// </summary>
        public static string Barrel {
            get {
                return ResourceManager.GetString("Barrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bart Cassidy.
        /// </summary>
        public static string BartCassidy {
            get {
                return ResourceManager.GetString("BartCassidy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer.
        /// </summary>
        public static string Beer {
            get {
                return ResourceManager.GetString("Beer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Jack.
        /// </summary>
        public static string BlackJack {
            get {
                return ResourceManager.GetString("BlackJack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calamity Janet.
        /// </summary>
        public static string CalamityJanet {
            get {
                return ResourceManager.GetString("CalamityJanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carabine.
        /// </summary>
        public static string Carabine {
            get {
                return ResourceManager.GetString("Carabine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat Balou.
        /// </summary>
        public static string CatBalou {
            get {
                return ResourceManager.GetString("CatBalou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputy.
        /// </summary>
        public static string Deputy {
            get {
                return ResourceManager.GetString("Deputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duel.
        /// </summary>
        public static string Duel {
            get {
                return ResourceManager.GetString("Duel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have {0} in play, you can not play another one.
        /// </summary>
        public static string DuplicatedCardExceptionMessageFormat {
            get {
                return ResourceManager.GetString("DuplicatedCardExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamite.
        /// </summary>
        public static string Dynamite {
            get {
                return ResourceManager.GetString("Dynamite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Gringo.
        /// </summary>
        public static string ElGringo {
            get {
                return ResourceManager.GetString("ElGringo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatling.
        /// </summary>
        public static string Gatling {
            get {
                return ResourceManager.GetString("Gatling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General store.
        /// </summary>
        public static string GeneralStore {
            get {
                return ResourceManager.GetString("GeneralStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indians.
        /// </summary>
        public static string Indians {
            get {
                return ResourceManager.GetString("Indians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jail.
        /// </summary>
        public static string Jail {
            get {
                return ResourceManager.GetString("Jail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesse Jones.
        /// </summary>
        public static string JessyJones {
            get {
                return ResourceManager.GetString("JessyJones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jourdonnais.
        /// </summary>
        public static string Jourdonnais {
            get {
                return ResourceManager.GetString("Jourdonnais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit Carlson.
        /// </summary>
        public static string KitCarlson {
            get {
                return ResourceManager.GetString("KitCarlson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky Duke.
        /// </summary>
        public static string LuckyDuke {
            get {
                return ResourceManager.GetString("LuckyDuke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed.
        /// </summary>
        public static string Missed {
            get {
                return ResourceManager.GetString("Missed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mustang.
        /// </summary>
        public static string Mustang {
            get {
                return ResourceManager.GetString("Mustang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlaw.
        /// </summary>
        public static string Outlaw {
            get {
                return ResourceManager.GetString("Outlaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panic.
        /// </summary>
        public static string Panic {
            get {
                return ResourceManager.GetString("Panic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paul Regret.
        /// </summary>
        public static string PaulRegret {
            get {
                return ResourceManager.GetString("PaulRegret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedro Ramirez.
        /// </summary>
        public static string PedroRamirez {
            get {
                return ResourceManager.GetString("PedroRamirez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remington.
        /// </summary>
        public static string Remington {
            get {
                return ResourceManager.GetString("Remington", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renegade.
        /// </summary>
        public static string Renegade {
            get {
                return ResourceManager.GetString("Renegade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rose Doolan.
        /// </summary>
        public static string RoseDoolan {
            get {
                return ResourceManager.GetString("RoseDoolan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saloon.
        /// </summary>
        public static string Saloon {
            get {
                return ResourceManager.GetString("Saloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schofield.
        /// </summary>
        public static string Schofield {
            get {
                return ResourceManager.GetString("Schofield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheriff.
        /// </summary>
        public static string Sheriff {
            get {
                return ResourceManager.GetString("Sheriff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sid Ketchum.
        /// </summary>
        public static string SidKetchum {
            get {
                return ResourceManager.GetString("SidKetchum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slab the Killer.
        /// </summary>
        public static string SlabTheKiller {
            get {
                return ResourceManager.GetString("SlabTheKiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stagecoach.
        /// </summary>
        public static string Stagecoach {
            get {
                return ResourceManager.GetString("Stagecoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suzy Lafayette.
        /// </summary>
        public static string SuzyLafayette {
            get {
                return ResourceManager.GetString("SuzyLafayette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volcanic.
        /// </summary>
        public static string Volcanic {
            get {
                return ResourceManager.GetString("Volcanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulture Sam.
        /// </summary>
        public static string VultureSam {
            get {
                return ResourceManager.GetString("VultureSam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wells Fargo.
        /// </summary>
        public static string WellsFargo {
            get {
                return ResourceManager.GetString("WellsFargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willi the Kid.
        /// </summary>
        public static string WillyTheKid {
            get {
                return ResourceManager.GetString("WillyTheKid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winchester.
        /// </summary>
        public static string Winchester {
            get {
                return ResourceManager.GetString("Winchester", resourceCulture);
            }
        }
    }
}
